#ifndef COLOURSORTER_FIRMWARE_CONFIG_H
#define COLOURSORTER_FIRMWARE_CONFIG_H

#define FW_SCHEDULER_TICK_US 1000U
#define FW_WATCHDOG_PERIOD_MS 50U
#define FW_BROWNOUT_MIN_MV 3100U
#define FW_ISR_UART_BUDGET_US 20U
#define FW_ISR_TIMER_BUDGET_US 10U
#define FW_QUEUE_DEPTH_MAX 8U

#endif
