from __future__ import annotations

MOTION_MODE = "motion_mode"
HOMING_MODE = "homing_mode"

MOTION_MODE_V4_FOLLOW_BELT = "FOLLOW_BELT"
MOTION_MODE_V4_TIME_WINDOW = "TIME_WINDOW"
MOTION_MODE_V4_MANUAL = "MANUAL"

HOMING_MODE_V4_AUTO_HOME = "AUTO_HOME"
HOMING_MODE_V4_SKIP_HOME = "SKIP_HOME"

MOTION_MODE_VALUES = (
    MOTION_MODE_V4_FOLLOW_BELT,
    MOTION_MODE_V4_TIME_WINDOW,
    MOTION_MODE_V4_MANUAL,
)
HOMING_MODE_VALUES = (
    HOMING_MODE_V4_AUTO_HOME,
    HOMING_MODE_V4_SKIP_HOME,
)

DEFAULT_MOTION_MODE = MOTION_MODE_V4_FOLLOW_BELT
DEFAULT_HOMING_MODE = HOMING_MODE_V4_SKIP_HOME

LEGACY_TO_V4 = {
    "ENCODER": MOTION_MODE_V4_FOLLOW_BELT,
    "TIME": MOTION_MODE_V4_TIME_WINDOW,
    "MANUAL": MOTION_MODE_V4_MANUAL,
    "ENABLED": HOMING_MODE_V4_AUTO_HOME,
    "DISABLED": HOMING_MODE_V4_SKIP_HOME,
}
