from coloursorter.config.enums import (
    DEFAULT_HOMING_MODE,
    DEFAULT_MOTION_MODE,
    HOMING_MODE_VALUES,
    MOTION_MODE_VALUES,
)

LANE_COUNT = 22
MOTION_MODES = list(MOTION_MODE_VALUES)
HOMING_MODES = list(HOMING_MODE_VALUES)
DEFAULT_MODE = DEFAULT_MOTION_MODE
DEFAULT_HOMING = DEFAULT_HOMING_MODE
